---
- name: Installing LAMP
  hosts: appserver
  become: true

  tasks:
  - name: Install Apache
    dnf:
      name: httpd
      state: latest

  - name: Start Apache
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Enable http Port
    firewalld:
      service: http
      permanent: yes
      state: enabled
  
  - name: Confirm http Port Status
    command: sudo firewall-cmd --permanent --list-all
    registar: port

  - debug: var=port.stdout_lines

  - name: Install MariaDB
    dnf:
      name: mariadb-server
    state: latest
    
  - name: Start MariaDB 
    systemd: 
      state: started
      enabled: yes
  
  - name: Confirm MYSQL status
    command: sudo mysql_secure_installation
    register: MYSQL
  
  - debug: sudo mysql

  - name: Install PHP
    dnf: 
      name: php-mysqlnd
    state: latest

  - name: Start PHP
    systemd:
      state: started
      enabled: yes

  


