---
- name: installing Oracle
  hosts: 
  become : 

  tasks:
  - name: Make Oracle directory
    file:
      path: ~/oracle
      state: directory

- name: g 512 oper
  group:
    name: oper
    state: present
    gid: 512

 - name: g 511 dba
   group:
     name: dba
     state: present
     gid: 511

 - name: create oinstall group
   group:
     name: dba
     state: oinstall
     gid: 510

 - name: oracle
   uid: 510
   group: oinstall
   shell: bin

 - name: Install the following
   yum: 
     name: '{{following}}'
     state: present
   vars:
     following items:
     - libcap
     - compat
     - libcap1
     - gcc
     - gcc-c++
     - glibc-2
     - glibc-2

 - name: move oracle
   command: mv oracle /var/tmp
   register: tmp

 - name: change command
   command: chmod 777 /var/tmp/oracle
   register: oracle

 - name: make U01 directory
   file:
     path: ~/U01
     state: directory

