---
- name: Installing Terraform
  hosts: appserver
  become: true

  tasks: 
  - name: Install Linux Utils
    yum:
      name: utils
      state: lastest

- name: Add Hashicorp Repo
  yum_repository:
    name: hashicorp
    description: hashicorp repo
    baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

  - name: Install Terraform
    yum:
      name: terraform
      state: latest

  - name: Download Awscli.zip
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: ~/

  - name: Unzip Awscli
    unarchive:
      src: ~/awscli-exe-linux-x86_64.zip
      dest: ~/
      remote_src: yes
      
  - name: Install AWSCLI
    command: ./aws/install