---
- name: Installing Terraform
  hosts: appserver
  become: true

  tasks: 
  - name: Install Amazon Linux
    yum:
      name: utils
      state: lastest

  - name: add repository 
    command: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    registar: amazon linux

  - name: Install Terraform
    command: sudo yum -y install terraform
    registar: terraform

